fieldLayouts:
  d72cf093-cb7d-42e1-9af2-6ea5bbc4d60b:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: c6b046a1-ec24-472d-94f0-435257a0adef
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e691c0e9-d735-4ffd-a455-db6c790e8080
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a456657d-ff3c-4c23-856d-8aa6025479c9
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
handle: contactThanks
hasTitleField: false
name: 'Contact Thanks'
section: b356c9f6-162f-4509-a15d-833193dba5df
sortOrder: 1
titleFormat: '{section.name|raw}'
