fieldLayouts:
  a6336ecb-eb82-42af-bc3f-2ea767c46372:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: c6b046a1-ec24-472d-94f0-435257a0adef
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e691c0e9-d735-4ffd-a455-db6c790e8080
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a456657d-ff3c-4c23-856d-8aa6025479c9
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Basic
        sortOrder: 1
handle: home
hasTitleField: false
name: Home
section: aceb11f3-b1d0-444b-a5df-b13455aba20e
sortOrder: 1
titleFormat: '{section.name|raw}'
