contentColumnType: string
fieldGroup: 571ec2c8-2af4-43c7-b870-67e1f93f713f
handle: email
instructions: ''
name: Email
searchable: true
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
